### ISSUE TITLE
vendor 登入後無法正常運作 及修改 event index 活動標題文字 置中

### ISSUE THREAD

**Issue by ElijahBecerra-Chen** [5xRuby-12th-RubyJoy/RubyJoy#142]
<img width="1166" alt="Screen Shot 2022-12-15 at 11 08 49 AM" src="https://user-images.githubusercontent.com/99235605/207763391-6e2d2a22-055e-4d26-82f0-5a0280c1d32a.png">

**Comment by ElijahBecerra-Chen** [comment]
<img width="1440" alt="Screen Shot 2022-12-15 at 11 12 46 AM" src="https://user-images.githubusercontent.com/99235605/207763863-2420e1b2-4c76-489e-b74b-8ca9508c783c.png">

Product index view

**Comment by Danny3766** [comment]
此 issue 已經解決 故關閉 issue
