### ISSUE TITLE
search bar 

### ISSUE THREAD

**Issue by ElijahBecerra-Chen** [5xRuby-12th-RubyJoy/RubyJoy#161]
<img width="1440" alt="Screen Shot 2022-12-16 at 10 45 05 AM" src="https://user-images.githubusercontent.com/99235605/208010214-6425703e-b75a-4244-b870-08e9041f5162.png">

**Comment by ElijahBecerra-Chen** [comment]
<img width="1355" alt="Screen Shot 2022-12-16 at 10 45 12 AM" src="https://user-images.githubusercontent.com/99235605/208010238-43cdf6d8-a44c-4f42-99c2-c6f8e2063f4c.png">

**Comment by Danny3766** [comment]
已於 issue/167 修正，merged。
