### ISSUE TITLE
store 訂單查詢頁面 優化

### ISSUE THREAD

**Issue by Danny3766** [5xRuby-12th-RubyJoy/RubyJoy#254]
<img width="1424" alt="2022-12-26_12 50 43" src="https://user-images.githubusercontent.com/112834036/209503076-601bf9d3-8601-4e01-96dc-78332b7270c1.png">
<img width="1329" alt="2022-12-26_12 51 02" src="https://user-images.githubusercontent.com/112834036/209503077-3a5a7559-4c65-4741-ac01-c2f2a3f771b6.png">

**Comment by ElijahBecerra-Chen** [comment]
merged
