### ISSUE TITLE
event show 「 前往結帳」 按鈕串接金流

### ISSUE THREAD

**Issue by ElijahBecerra-Chen** [5xRuby-12th-RubyJoy/RubyJoy#96]
🎯 Event show 已下判斷式 （ 如果不是 event owner 會顯示前往結帳 ），金流可進場串結帳路徑

**Comment by chocolin1226** [comment]
連結
可以寫下面這樣

<%= buy_product_path(@product) %>

就可以進入購買頁面
但目前抓不到product 的id要再處理

**Comment by ElijahBecerra-Chen** [comment]
done and merged
